### ISSUE TITLE
Design of minute, second, primemod, doubleprimemod

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/Merriweather-Sans#5]
1. In Light, Regular, Black, `doubleprimemod` is composed of two overlapping `minute` components.
One of the `minute` components should be shifted horizontally, like in the italic masters.
2. In Light Italic, Regular Italic, Black Italic, `primemod` has `top` and `_top` anchors it shouldn’t have.
3. The advance width are not consistent, for example in Regular, `minute` is 668 but `primemod` is 586, and the right side bearing of `doubleprimemod` or `second` are different from that of `minute` as well.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1923747/78124077-11c5f300-7407-11ea-9234-ff96557727ee.png">

I have a fix to change it as follows:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/1923747/78124132-273b1d00-7407-11ea-9735-140ef6a29293.png">

Note that the difference between `primemod`, `doubleprimemod` and `minute`, `second` is mostly semantic. `primemod`, `doubleprimemod` are meant to be used as letters whereas `minute`, `second` are meant to be used with numbers. Users sometimes don’t make that distinction.

**Comment by pichotta** [comment]
The fix is an improvement to both the aesthetics and functionality.
