### ISSUE TITLE
GF QA

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Merriweather-Sans#7]
• Broken bar in Italic styles are not interpolating correctly

![merriweather_broken_bar](https://user-images.githubusercontent.com/7525512/78539714-e9653c80-77ea-11ea-9f89-2f9d10297abe.gif)

• I don't know what the underlying issue is but the i has a major bug

![merriweather_iissue](https://user-images.githubusercontent.com/7525512/78540191-b0799780-77eb-11ea-880e-90b8d791d700.gif)

_OS X Safari_

![merriweather_itightness](https://user-images.githubusercontent.com/7525512/78540203-b3748800-77eb-11ea-9b9d-75e2f7cc4676.gif)

_Win Chrome_

**Comment by pichotta** [comment]
Made change to /i and /j which were composites referencing dotless versions and dot accent.
Fixed contour indexes of /brokenbar

**Comment by pichotta** [comment]
@moyogo 
see the Font Bakery fails in report for the italics 
gftools qa -f vf/MerriweatherSans-Italic[wght].ttf -gfb --diffenator --fontbakery

![Italic FB report 2020-04-09 at 10 08 26 PM](https://user-images.githubusercontent.com/6576107/78956121-51e44000-7aaf-11ea-8853-c9994fe87032.png)

**Comment by moyogo** [comment]
@pichotta
1. Sorry I missed the /i issue earlier.  There is a "_ogonek" anchor in /i, which fontmake uses to turn /i into a mark glyph. The anchor should be called "ogonek" instead.
In general, there is a design issue with /ogonekcomb and the letters with ogonek /aogonek, /eogonek, /iogonek, /oogonek, /uogonek, definitely in Light, Regular and Black:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1923747/78992420-18edaf00-7b33-11ea-8081-1166218a4d25.png">
but less so in Light Italic, Italic and UltraBold Italic:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/1923747/78992472-37ec4100-7b33-11ea-8443-c938a464519a.png">

2. For UltraBold Italic, fontbakery is happy is it is renamed ExtraBold. We can rename UltraBold to ExtraBold, or we can modify fontbakery so it accepts UltraBold (and also UltraLight or Heavy which are in the OpenType specification, or even UltraBlack as alternates of ExtraLight, Black and ExtraBlack respetively).

3. There is no wght=800 equivalent to UltraBold Italic in the Romans, but https://fonts.google.com/specimen/Merriweather+Sans currently has a wght=800 UltraBold.

@m4rc1e Can you comment on 2 and 3?

**Comment by moyogo** [comment]
There are also design issues with the uppercase letters with ogonek /Aogonek, /Eogonek, /Iogonek, /Oogonek, /Uogonek
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1923747/78993009-99f97600-7b34-11ea-8ec3-2631183d96a8.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1923747/78993013-9f56c080-7b34-11ea-969c-a90dfb49ff5e.png">

**Comment by moyogo** [comment]
Fixed in #8
